services:
    app:
        build:
            context: frontend
            args:
                BACKEND_URL: http://backend:8080
                NEXT_PUBLIC_MAPLIBRE_STYLE: ${NEXT_PUBLIC_MAPLIBRE_STYLE}
                NEXT_PUBLIC_MAPBOX_STYLE: ${NEXT_PUBLIC_MAPBOX_STYLE:-mapbox://styles/mapbox/standard}
                NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
        restart: unless-stopped
        environment:
            BACKEND_URL: http://backend:8080
        ports:
            - "3000:3000"
        depends_on:
            - backend
        labels:
            dev.orbstack.domains: sosbor.local

    backend:
        build:
            context: pb
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - pb_data:/pb/pb_data

volumes:
    pb_data:
